version: '3.8'

services:
  webapi:
    container_name: ambev_developer_evaluation_webapi
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=AmbevDeveloperEvaluation;User Id=sa;Password=Your_password123;TrustServerCertificate=True
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - sqlserver

  sqlserver:
    container_name: ambev_developer_evaluation_sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: